"use client"

import React, { forwardRef } from 'react'
import { AstrologyUserData } from '@/types/astrology'

interface PDFReportTemplateProps {
    userData: AstrologyUserData | null
}

const PDFReportTemplate = forwardRef<HTMLDivElement, PDFReportTemplateProps>(({ userData }, ref) => {
    if (!userData) return null

    // Helper for A4 scaling (210mm width)
    // We'll use a fixed pixel width (e.g. 794px for 96dpi) and allow scaling
    return (
        <div ref={ref} className="bg-white text-slate-900 absolute top-[-10000px] left-[-10000px] w-[794px]">

            {/* PAGE 1: COVER */}
            <div className="w-[794px] h-[1123px] relative bg-slate-900 text-white p-20 flex flex-col justify-between overflow-hidden">
                {/* Decorative Background */}
                <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-purple-500/20 blur-[100px] rounded-full" />
                <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-cyan-500/20 blur-[100px] rounded-full" />

                <div className="relative z-10 border-4 border-double border-amber-500/30 h-full p-12 flex flex-col items-center justify-center text-center">
                    <div className="mb-8">
                        <span className="text-6xl text-amber-500">✶</span>
                    </div>

                    <h1 className="text-5xl font-serif font-bold tracking-wider mb-4 text-transparent bg-clip-text bg-gradient-to-r from-amber-200 to-amber-500">
                        COSMIC PATH
                    </h1>
                    <h2 className="text-xl uppercase tracking-[0.3em] text-gray-400 mb-20">
                        Destiny Report
                    </h2>

                    <div className="space-y-4 mb-20">
                        <h3 className="text-3xl font-bold text-white">{userData.name}</h3>
                        <div className="w-20 h-1 bg-amber-500 mx-auto" />
                        <p className="text-lg text-gray-300">
                            {userData.dob} • {userData.tob}
                        </p>
                        <p className="text-gray-400">{userData.pob}</p>
                    </div>

                    <div className="mt-auto">
                        <p className="text-xs text-gray-500 uppercase tracking-widest">
                            Generated by Cosmic Path AI
                        </p>
                    </div>
                </div>
            </div>

            {/* PAGE 2: PLANETARY SNAPSHOT */}
            <div className="w-[794px] h-[1123px] bg-white p-16 flex flex-col">
                <h3 className="text-2xl font-serif font-bold text-slate-800 border-b-2 border-amber-500 pb-2 mb-8">
                    Planetary Snapshot
                </h3>

                {/* Basic Info Grid */}
                <div className="grid grid-cols-2 gap-8 mb-12">
                    <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                        <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Ascendant (Lagna)</h4>
                        <div className="text-3xl font-bold text-slate-800">{userData.lagna}</div>
                        <p className="text-slate-600 mt-1">Lord: {userData.lagnaLord}</p>
                    </div>
                    <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
                        <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Moon Sign (Rashi)</h4>
                        <div className="text-3xl font-bold text-slate-800">{userData.moonSign}</div>
                        <p className="text-slate-600 mt-1">Nakshatra: {userData.nakshatra}</p>
                    </div>
                </div>

                {/* Planetary Table */}
                <div className="mb-12">
                    <table className="w-full text-left text-sm border-collapse">
                        <thead>
                            <tr className="bg-slate-900 text-white">
                                <th className="p-3">Planet</th>
                                <th className="p-3">Sign</th>
                                <th className="p-3">House</th>
                                <th className="p-3">Degree</th>
                                <th className="p-3">Nakshatra</th>
                            </tr>
                        </thead>
                        <tbody>
                            {Object.entries(userData.planetaryPositions).map(([key, planet]) => (
                                <tr key={key} className="border-b border-slate-200 odd:bg-slate-50">
                                    <td className="p-3 font-medium capitalize">{key}</td>
                                    <td className="p-3">{planet.sign}</td>
                                    <td className="p-3">{planet.house}</td>
                                    <td className="p-3 font-mono text-slate-500">{planet.degree}</td>
                                    <td className="p-3">{planet.nakshatra}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {/* Nature / Elements (Placeholder for logic if needed) */}
                <div className="bg-amber-50 border border-amber-200 p-6 rounded-lg">
                    <h4 className="font-bold text-amber-800 mb-2">Core Nature</h4>
                    <p className="text-slate-700 leading-relaxed">
                        Your ascendant in {userData.lagna} characterizes you as someone with strong {userData.lagnaLord} energy.
                        Combined with your {userData.moonSign} moon, your emotional self matches {userData.moonSignLord}'s qualities.
                    </p>
                </div>
            </div>

            {/* PAGE 3: DETAILED PREDICTIONS */}
            <div className="w-[794px] h-[1123px] bg-white p-16 flex flex-col">
                <h3 className="text-2xl font-serif font-bold text-slate-800 border-b-2 border-amber-500 pb-2 mb-8">
                    Life Path Analysis
                </h3>

                <div className="space-y-8">
                    <ReportSection title="Career & Destiny" content={userData.lifePredictions?.career || "Calculating..."} />
                    <ReportSection title="Love & Relationships" content={userData.lifePredictions?.marriage || "Calculating..."} />
                    <ReportSection title="Wealth & Finance" content={userData.lifePredictions?.finance || "Calculating..."} />
                    <ReportSection title="Health & Vitality" content={userData.lifePredictions?.health || "Calculating..."} />
                </div>

                <div className="mt-12 p-6 bg-slate-900 text-slate-200 rounded-xl">
                    <h4 className="text-amber-500 font-bold mb-3 uppercase tracking-wider text-sm">Vital Statistics</h4>
                    <div className="grid grid-cols-2 gap-4 text-sm">
                        <div className="flex justify-between border-b border-slate-700 pb-2">
                            <span>Life Path Number</span>
                            <span className="font-bold text-white">{userData.lifePathNumber}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-700 pb-2">
                            <span>Current Mahadasha</span>
                            <span className="font-bold text-white">{userData.currentMahadasha}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-700 pb-2">
                            <span>Sade Sati Status</span>
                            <span className="font-bold text-white">
                                {userData.sadeSati && userData.sadeSati.length > 0 ? userData.sadeSati[0].phase : "None"}
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    )
})

function ReportSection({ title, content }: { title: string, content: string }) {
    return (
        <div className="bg-white">
            <h4 className="text-lg font-bold text-slate-800 mb-2 flex items-center">
                <span className="w-2 h-2 bg-amber-500 rounded-full mr-3" />
                {title}
            </h4>
            <p className="text-slate-600 leading-relaxed pl-5">
                {content}
            </p>
        </div>
    )
}

PDFReportTemplate.displayName = "PDFReportTemplate"

export default PDFReportTemplate
